### ISSUE TITLE
curl and --data error in windows (Page 98)

### ISSUE THREAD

**Issue by bjohn22** [paiml/practical-mlops-book#3]
Solution: I added **GitBash** to the windows environment and the command worked in bash. I will leave this issue open for other users. 
I believe the issue has to do the with `curl` not being able to convert the `Str` data to `json` format in `powershell`. 

I am following along with Chapter 4 on my windows 10 computer.
the `curl ....` did not work so I swapped that for `Get-Command` which worked but I got and `Get-Command : The term '--data' is not recognized as the name of a cmdlet, function..`

Here is the full command:
`PS C:\Users\xxxxx\Documents\dir> Get-Command -X POST -H "Content-Type: application/JSON" --data '["Containers are more or less"]' http://xxx.xxx.x.x:xxxx/predict`
Can windows users use this book? I can't seem convert my windows system to linux at the moment.

**Comment by alfredodeza** [comment]
The contents of the book were not tested on Windows environments. They should work fine in Linux and OSX though. I don't think we can revise all commands to ensure they work on Windows. I suggest you try WSL to have a Linux environment that you can use on Windows
